# Grid & game
grid_rows: 6
grid_cols: 7
connect_k: 4
max_steps_per_episode: 100

# Training
num_episodes: 64000
batch_size: 512
gamma: 0.99
gae_lambda: 0.95
entropy_coef: 0.01
value_coef: 0.5
learning_rate: 0.0003
seed: 42
opponent_update_interval: 8000

# Model architecture
actor_layers: [128, 128]

# Checkpoint & logging
save_interval: 1000
log_interval: 10
results_dir: "results"

# Evaluation
eval_episodes: 
checkpoint: "/home/tabbott/Software/rl_connect_n_two_agent/results/20250523-215110/checkpoint_13400.pt"

# Device
use_cuda: true
