num_episodes: 10000
batch_size: 32
evaluate_every: 500
random_seed: 42

grid_rows: 6
grid_cols: 7
connect_k: 4
max_steps_per_episode: 42

agent_type: dqn
dqn:
  lr: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 5000
  target_update_freq: 1000

eval_opponents:
  - type: random
  - type: minimax
    depth: 2
